# Generated by Django 3.2.3 on 2021-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=246)),
                ('mobileno', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(default='', max_length=400)),
                ('Photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile/')),
                ('password', models.TextField(default='', max_length=200)),
                ('Register_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
