# Generated by Django 3.2.3 on 2021-06-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_raw_data_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_nm', models.CharField(default='', max_length=200)),
                ('cus_em', models.EmailField(default='', max_length=200)),
                ('cus_con', models.PositiveIntegerField(default=0)),
                ('cus_add1', models.TextField(default='')),
                ('cus_add2', models.TextField(default='')),
                ('cus_regi_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cus_photo', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Cus_Photo/')),
                ('cus_pass', models.CharField(default='', max_length=200)),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.raw_data')),
            ],
        ),
    ]
