# Generated by Django 3.2.3 on 2021-06-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cus_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cus_data',
            name='cus_add2',
        ),
    ]
