# Generated by Django 3.2.3 on 2021-06-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_cus_data_cus_add2'),
    ]

    operations = [
        migrations.CreateModel(
            name='mg_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mg_em', models.EmailField(default='', max_length=200)),
                ('mg_con', models.PositiveIntegerField(default=0)),
                ('mg_mass', models.TextField(default='')),
                ('mg_regi_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mg_nm', models.CharField(default='', max_length=200)),
                ('cus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cus_data')),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.raw_data')),
            ],
        ),
    ]
