# Generated by Django 3.2.3 on 2021-06-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_mg_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nm', models.CharField(default='', max_length=200)),
                ('pro_pr', models.PositiveIntegerField(default=0)),
                ('pro_qty', models.PositiveIntegerField(default=0)),
                ('pro_img', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='ProductPic/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.raw_data')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_price', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Waiting', max_length=20)),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.raw_data')),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cus_data')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company_product')),
            ],
        ),
    ]
